

build:
	gcc -std=c++17 picture.hpp line.hpp drawable.hpp rectangle.hpp  ball.hpp ball.cpp rectangle.cpp line.cpp picture.cpp main.cpp -o main -lsfml-graphics -lsfml-window -lsfml-system -lstdc++
run:
	./main
clean: 
	rm -fr main
